# Generated by Django 4.2.1 on 2023-05-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='comm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.community'),
        ),
    ]
